//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetBanking
    {
        public int AcccountNumber { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public int TransactionPassword { get; set; }
        public int ConfirmTransactionPassword { get; set; }
        public Nullable<byte> OTP { get; set; }
    }
}
