//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class savingsaccount
    {
        public int accountId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> AdharNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string Landmark { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string OccupationType { get; set; }
        public string Sourceincome { get; set; }
        public Nullable<decimal> Grossalary { get; set; }
    }
}
