//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int Userid { get; set; }
        public int TransactionNumber { get; set; }
        public int FromAccount { get; set; }
        public int ToAccount { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<decimal> WithdrawAmount { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TypeOfTransaction { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
    }
}
